# Prediksi Harga Rumah dengan CSV

In [45]:
import pandas as pd

df = pd.read_csv('../../Dataset/data_rumah.csv', encoding='utf-8', sep=';')
df.head()

# Ini Milyar ygy Harganya

NO                                         NAMA RUMAH       HARGA   LB  \
0   1  Rumah Murah Hook Tebet Timur, Tebet, Jakarta S...  3800000000  220   
1   2  Rumah Modern di Tebet dekat Stasiun, Tebet, Ja...  4600000000  180   
2   3  Rumah Mewah 2 Lantai Hanya 3 Menit Ke Tebet, T...  3000000000  267   
3   4           Rumah Baru Tebet, Tebet, Jakarta Selatan   430000000   40   
4   5  Rumah Bagus Tebet komp Gudang Peluru lt 350m, ...  9000000000  400   

    LT  KT  KM  GRS  
0  220   3   3    0  
1  137   4   3    2  
2  250   4   4    4  
3   25   2   2    0  
4  355   6   5    3

In [46]:
import numpy as np

df_feature = df.drop(['HARGA', 'NAMA RUMAH', 'NO'], axis=1)
print(df_feature.head())

df_label = df.drop(['LT', 'LB', 'KT', 'KM', 'GRS', 'NAMA RUMAH','NO'], axis=1)
print(df_label.head())

    LB   LT  KT  KM  GRS
0  220  220   3   3    0
1  180  137   4   3    2
2  267  250   4   4    4
3   40   25   2   2    0
4  400  355   6   5    3
        HARGA
0  3800000000
1  4600000000
2  3000000000
3   430000000
4  9000000000


In [47]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df_feature, df_label, test_size=0.2, random_state=0)
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()
y_train = y_train.to_numpy().reshape(-1, 1)
y_test = y_test.to_numpy().reshape(-1, 1)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[100 130   3   2   2]
 [525 330   4   4   3]
 [280 220   4   3   4]
 ...
 [300 300   5   4   2]
 [350 250   5   4   1]
 [300 200   5   4   4]]
[[150 135   5   3   3]
 [400 429   9   5   5]
 [350 210   4   4   1]
 ...
 [300 154   5   3   3]
 [100  56   3   2   0]
 [420 430   7   4   2]]
[[ 2800000000]
 [16000000000]
 [ 7000000000]
 [ 7900000000]
 [18500000000]
 [ 9500000000]
 [ 3500000000]
 [12500000009]
 [ 4500000000]
 [ 1100000000]
 [ 2100000000]
 [17500000000]
 [ 2500000000]
 [ 3750000000]
 [ 6000000000]
 [ 2200000000]
 [ 8500000000]
 [ 6500000000]
 [ 6700000000]
 [ 3500000000]
 [ 2600000000]
 [ 2600000000]
 [  850000000]
 [ 4000000000]
 [ 3000000000]
 [12500000000]
 [ 4300000000]
 [ 3700000000]
 [15000000000]
 [23000000000]
 [10000000000]
 [ 2400000000]
 [ 8000000000]
 [18000000000]
 [ 8000000000]
 [ 2250000000]
 [ 9800000000]
 [21000000000]
 [ 3800000000]
 [ 8100000000]
 [ 2850000000]
 [ 5900000000]
 [ 1900000000]
 [ 4700000000]
 [ 2590000000]
 [ 6250000000]
 [ 6100000000]
 [ 3200

In [48]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import ModelCheckpoint

model = Sequential([
    Dense(10, input_dim=5, activation='relu'),
    Dense(10, activation='relu'),
    Dense(1)
])

model.compile(optimizer='RMSprop', loss='mse')

checkpoint = ModelCheckpoint('prediksi_harga_rumah_csv.h5', monitor='loss', mode='min', save_best_only=True, verbose=0)

print("Modeling dimulai")
history = model.fit(x_train, y_train, epochs=1000, callbacks=[checkpoint], verbose=0)
print("Modeling selesai")

c:\Users\anfiniti\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


TypeError: ModelCheckpoint.__init__() got an unexpected keyword argument 'epochs'

In [ ]:
prediksinya = model.predict(x_train)

print("Prediksi Harga Rumahnya:")
for i, prediction in enumerate(prediksinya):
    print(f"Rumah {i+1}: Prediksi Harga = Rp. {prediction[0]:.2f}")

26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
Prediksi Harga Rumahnya:
Rumah 1: Prediksi Harga = Rp. 1021710.69
Rumah 2: Prediksi Harga = Rp. 3723715.50
Rumah 3: Prediksi Harga = Rp. 2198707.00
Rumah 4: Prediksi Harga = Rp. 2646162.50
Rumah 5: Prediksi Harga = Rp. 5048185.00
Rumah 6: Prediksi Harga = Rp. 3241620.00
Rumah 7: Prediksi Harga = Rp. 1302441.75
Rumah 8: Prediksi Harga = Rp. 3466147.00
Rumah 9: Prediksi Harga = Rp. 1539026.75
Rumah 10: Prediksi Harga = Rp. 618456.38
Rumah 11: Prediksi Harga = Rp. 1396577.00
Rumah 12: Prediksi Harga = Rp. 5073868.50
Rumah 13: Prediksi Harga = Rp. 1014223.00
Rumah 14: Prediksi Harga = Rp. 1747993.00
Rumah 15: Prediksi Harga = Rp. 1554036.38
Rumah 16: Prediksi Harga = Rp. 738318.69
Rumah 17: Prediksi Harga = Rp. 2556910.25
Rumah 18: Prediksi Harga = Rp. 2199455.50
Rumah 19: Prediksi Harga = Rp. 2308733.75
Rumah 20: Prediksi Harga = Rp. 1684166.12
Rumah 21: Prediksi Harga = Rp. 1508510.75
Rumah 22: Prediksi Harga = Rp. 1189088.50
Rumah 23: Prediksi Har

In [ ]:
errors = np.abs(y_train - prediksinya.flatten())
print(f"Error rata-rata: {np.mean(errors):.2f}")

Error rata-rata: 7598571024.39
