# Prediksi Harga Rumah dengan CSV

In [49]:
import pandas as pd

df = pd.read_csv('../../Dataset/data_rumah.csv', encoding='utf-8', sep=';')
df.head()

# Ini Milyar ygy Harganya

NO                                         NAMA RUMAH       HARGA   LB  \
0   1  Rumah Murah Hook Tebet Timur, Tebet, Jakarta S...  3800000000  220   
1   2  Rumah Modern di Tebet dekat Stasiun, Tebet, Ja...  4600000000  180   
2   3  Rumah Mewah 2 Lantai Hanya 3 Menit Ke Tebet, T...  3000000000  267   
3   4           Rumah Baru Tebet, Tebet, Jakarta Selatan   430000000   40   
4   5  Rumah Bagus Tebet komp Gudang Peluru lt 350m, ...  9000000000  400   

    LT  KT  KM  GRS  
0  220   3   3    0  
1  137   4   3    2  
2  250   4   4    4  
3   25   2   2    0  
4  355   6   5    3

In [50]:
import numpy as np

df_feature = df.drop(['HARGA', 'NAMA RUMAH', 'NO'], axis=1)
print(df_feature.head())

df_label = df.drop(['LT', 'LB', 'KT', 'KM', 'GRS', 'NAMA RUMAH','NO'], axis=1)
print(df_label.head())

    LB   LT  KT  KM  GRS
0  220  220   3   3    0
1  180  137   4   3    2
2  267  250   4   4    4
3   40   25   2   2    0
4  400  355   6   5    3
        HARGA
0  3800000000
1  4600000000
2  3000000000
3   430000000
4  9000000000


In [51]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df_feature, df_label, test_size=0.2, random_state=0)
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()
y_train = y_train.to_numpy().reshape(-1, 1)
y_test = y_test.to_numpy().reshape(-1, 1)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[100 130   3   2   2]
 [525 330   4   4   3]
 [280 220   4   3   4]
 ...
 [300 300   5   4   2]
 [350 250   5   4   1]
 [300 200   5   4   4]]
[[150 135   5   3   3]
 [400 429   9   5   5]
 [350 210   4   4   1]
 ...
 [300 154   5   3   3]
 [100  56   3   2   0]
 [420 430   7   4   2]]
[[ 2800000000]
 [16000000000]
 [ 7000000000]
 [ 7900000000]
 [18500000000]
 [ 9500000000]
 [ 3500000000]
 [12500000009]
 [ 4500000000]
 [ 1100000000]
 [ 2100000000]
 [17500000000]
 [ 2500000000]
 [ 3750000000]
 [ 6000000000]
 [ 2200000000]
 [ 8500000000]
 [ 6500000000]
 [ 6700000000]
 [ 3500000000]
 [ 2600000000]
 [ 2600000000]
 [  850000000]
 [ 4000000000]
 [ 3000000000]
 [12500000000]
 [ 4300000000]
 [ 3700000000]
 [15000000000]
 [23000000000]
 [10000000000]
 [ 2400000000]
 [ 8000000000]
 [18000000000]
 [ 8000000000]
 [ 2250000000]
 [ 9800000000]
 [21000000000]
 [ 3800000000]
 [ 8100000000]
 [ 2850000000]
 [ 5900000000]
 [ 1900000000]
 [ 4700000000]
 [ 2590000000]
 [ 6250000000]
 [ 6100000000]
 [ 3200

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import ModelCheckpoint

model = Sequential([
    Dense(64, input_dim=5, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

checkpoint = ModelCheckpoint('prediksi_harga_rumah_csv.h5', monitor='loss', mode='min', save_best_only=True, verbose=0)

print("Modeling dimulai")
history = model.fit(x_train, y_train, epochs=10000, callbacks=[checkpoint], verbose=0)
print("Modeling selesai")

Modeling dimulai
Modeling selesai


In [65]:
prediksinya = model.predict(x_train)

print("Prediksi Harga Rumahnya:")
for i, prediction in enumerate(prediksinya):
    print(f"Rumah {i+1}: Prediksi Harga = Rp. {prediction[0]:.2f}")

26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Prediksi Harga Rumahnya:
Rumah 1: Prediksi Harga = Rp. nan
Rumah 2: Prediksi Harga = Rp. nan
Rumah 3: Prediksi Harga = Rp. nan
Rumah 4: Prediksi Harga = Rp. nan
Rumah 5: Prediksi Harga = Rp. nan
Rumah 6: Prediksi Harga = Rp. nan
Rumah 7: Prediksi Harga = Rp. nan
Rumah 8: Prediksi Harga = Rp. nan
Rumah 9: Prediksi Harga = Rp. nan
Rumah 10: Prediksi Harga = Rp. nan
Rumah 11: Prediksi Harga = Rp. nan
Rumah 12: Prediksi Harga = Rp. nan
Rumah 13: Prediksi Harga = Rp. nan
Rumah 14: Prediksi Harga = Rp. nan
Rumah 15: Prediksi Harga = Rp. nan
Rumah 16: Prediksi Harga = Rp. nan
Rumah 17: Prediksi Harga = Rp. nan
Rumah 18: Prediksi Harga = Rp. nan
Rumah 19: Prediksi Harga = Rp. nan
Rumah 20: Prediksi Harga = Rp. nan
Rumah 21: Prediksi Harga = Rp. nan
Rumah 22: Prediksi Harga = Rp. nan
Rumah 23: Prediksi Harga = Rp. nan
Rumah 24: Prediksi Harga = Rp. nan
Rumah 25: Prediksi Harga = Rp. nan
Rumah 26: Prediksi Harga = Rp. nan
Rumah 27: Prediksi Harga = Rp. nan


In [57]:
errors = np.abs(y_train - prediksinya.flatten())
print(f"Error rata-rata: {np.mean(errors):.2f}")

Error rata-rata: 7600827577.19
